title: Shinibali Bhattacharyya
description: Notes from training small language models from scratch.
url: "https://shinibali.github.io"
baseurl: ""
theme: minima
header_pages:
  - about.md
plugins:
  - jekyll-feed
show_excerpts: true
twitter_username: ShinibaliB
github_username: Shinibali
linkedin_username: shinibali-bhattacharyya
